config/routes.rb
 FutsalApp::Application.routes.draw do
   root  to: 'places#index'

   controller :static_pages do
     get :about, :contact, :news, :ochiai, :toshimaen, :nerima
   end

   resources :places do
     member do
       get :search, :followers
     end
   end
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :place
end

app/models/map.rb
class Map < ActiveRecord::Base
	geocoded_by :address
	after_validation :geocode
end

app/models/nerima.rb
class Nerima < ActiveRecord::Base
	validates :url, uniqueness: true
end

app/models/ochiai.rb
class Ochiai < ActiveRecord::Base
	validates :url, uniqueness: true
end

app/models/place.rb
class Place < ActiveRecord::Base
  has_many :events,dependent: :destroy
end

app/models/toshimaen.rb
class Toshimaen < ActiveRecord::Base
	validates :url, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :set_place, only: [:show, :edit, :update, :destroy]

  def index
    @places = Place.all
  end

  def show
  end

  def edit
  end

  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  def set_place
    @place = Place.find(params[:id])
  end

  def place_params
    params.require(:place).permit(:name, :address, :description)
  end
  
end

app/controllers/static_pages_controller.rb
require "nokogiri"
require "open-uri"
require "active_record"

class StaticPagesController < ApplicationController

	def home
    @detail = [] 
    @date = [] 
    @url = [] 
    @title = [] 
		@detail_toshi = []
		@date_toshi = []
		@url_toshi = []
		@title_toshi =[]
		@detail_nerima =[]
		@date_nerima = []
		@url_nerima = []
		@title_nerima = []


	  @maps = Map.all
	  @hash = Gmaps4rails.build_markers(@maps) do |user, marker|
		  marker.lat user.latitude
		  marker.lng user.longitude
		  marker.infowindow user.description
	  end
		
    	for i in 1..3
        url = "http://labola.jp/reserve/shop/2013/menu/personal/#{i}"
        page_source = open(url)
        doc = Nokogiri::HTML.parse(page_source,nil)
        doc.css("table.blue_table > tr").each do |elem|
          elem.css("td > a").each do |o|
				    Ochiai.create(:url => "http://labola.jp#{o[:href]}")
          end
        end
		  end
    
    items = Ochiai.find(1,2,3)

    items.each do |item| 
      page_source = open(item.url)
      doc = Nokogiri::HTML.parse(page_source,nil)
      doc.css("table.blue_table").each do |elem|
	      elem.css("tr:nth-child(5) > td").each do |o|
			   	@detail.push(o.text.scan(/[\d\-]+/))
					elem.css("tr:nth-child(2) > td").each do |x|
					  @date.push(x.text)
						elem.css("tr:nth-child(1) > td > b").each do |y|
							@title.push(y.text)
						end
		      end
				end
		  end
			@url.push(item.url)
    end

		items_toshi = Toshimaen.find(1,2,3)

    items_toshi.each do |item| 
      page_source = open(item.url)
      doc = Nokogiri::HTML.parse(page_source,nil)
      doc.css("table.blue_table").each do |elem|
	      elem.css("tr:nth-child(5) > td").each do |o|
			   	@detail_toshi.push(o.text.scan(/[\d\-]+/))
					elem.css("tr:nth-child(2) > td").each do |x|
					  @date_toshi.push(x.text)
						elem.css("tr:nth-child(1) > td > b").each do |y|
							@title_toshi.push(y.text)
						end
		      end
				end
		  end
			@url_toshi.push(item.url)
    end

		items_nerima = Nerima.find(1,2,3)

      items_nerima.each do |item| 
      page_source = open(item.url)
      doc = Nokogiri::HTML.parse(page_source,nil)
      doc.css("table.blue_table").each do |elem|
	      elem.css("tr:nth-child(5) > td").each do |o|
			   	@detail_nerima.push(o.text.scan(/[\d\-]+/))
					elem.css("tr:nth-child(2) > td").each do |x|
					  @date_nerima.push(x.text)
						elem.css("tr:nth-child(1) > td > b").each do |y|
							@title_nerima.push(y.text)
						end
		      end
				end
		  end
			@url_nerima.push(item.url)
    end
	end

	def place
	end

	def about
	end

	def contact
	end

	def news
	end

  def ochiai
    @events = Event.where(place_id: 1)
  end

	def toshimaen
		@detail = [] 
    @date = [] 
    @url = [] 
    @title = [] 
    for i in 1..3
      url = "http://labola.jp/reserve/shop/880/menu/personal/#{i}"
      page_source = open(url)
      doc = Nokogiri::HTML.parse(page_source,nil)
      doc.css("table.blue_table > tr").each do |elem|
        elem.css("td > a").each do |o|
				  Toshimaen.create(:url => "http://labola.jp#{o[:href]}")
				  #@array.push("http://labola.jp#{o[:href]}")
        end
      end
		end
    
    items = Toshimaen.all

    items.each do |item| 
      page_source = open(item.url)
      doc = Nokogiri::HTML.parse(page_source,nil)
      doc.css("table.blue_table").each do |elem|
	      elem.css("tr:nth-child(5) > td").each do |o|
			   	@detail.push(o.text.scan(/[\d\-]+/))
					elem.css("tr:nth-child(2) > td").each do |x|
					  @date.push(x.text)
				    elem.css("tr:nth-child(1) > td > b").each do |y|
						  @title.push(y.text)
					  end
		      end
				end
		  end
		@url.push(item.url)
   end
	end

	def nerima
    @detail = [] 
    @date = [] 
    @url = [] 
    @title = [] 
    for i in 1..3
      url = "http://labola.jp/reserve/shop/785/menu/personal/#{i}"
      page_source = open(url)
      doc = Nokogiri::HTML.parse(page_source,nil)
      doc.css("table.blue_table > tr").each do |elem|
        elem.css("td > a").each do |o|
				  Nerima.create(:url => "http://labola.jp#{o[:href]}")
				  #@array.push("http://labola.jp#{o[:href]}")
        end
      end
		end
    
    items = Nerima.all

    items.each do |item| 
      page_source = open(item.url)
      doc = Nokogiri::HTML.parse(page_source,nil)
      doc.css("table.blue_table").each do |elem|
	      elem.css("tr:nth-child(5) > td").each do |o|
			   	@detail.push(o.text.scan(/[\d\-]+/))
					elem.css("tr:nth-child(2) > td").each do |x|
					  @date.push(x.text)
				    elem.css("tr:nth-child(1) > td > b").each do |y|
						  @title.push(y.text)
					  end
		      end
				end
		  end
		@url.push(item.url)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # ページごとの完全なタイトルを返します。
  def full_title(page_title)
    base_title = "futsalApp"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="#">futsal_app</a>
		by shiro
	</small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
			<li><%= link_to "News", news_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "個サルapp", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home",    root_path %></li>
          <li><%= link_to "コート場",    places_path %></li>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
			<%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/places/edit.html.erb
<h1>フットサルコート編集</h1>

app/views/places/index.html.erb
<h2>フットサルコート一覧</h2>
<div class="container-fluid">
  <table class="table table-striped">
    <tbody>
      <% @places.each do |place| %>
        <tr>
          <td width="60%">
            <%= place.name %>
          </td>
          <td>
            <%= link_to '<button type="button" class="btn btn-primary"><i class="glyphicon glyphicon-info-sign"></i>　表示</button>'.html_safe, edit_place_path(place) %> 
            <%= link_to '<button type="button" class="btn btn-danger"><i class="glyphicon glyphicon-remove-sign"></i>　削除</button>'.html_safe, edit_place_path(place), method: :delete, data: { confirm: '本当に削除しますか' } %> 
                    </button>

          </td>

        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/places/show.html.erb
<% content_for :name do %>
フットサルコート詳細情報
<% end %>
<p id="notice"><%= notice %></p>

<div　class="container">
  <div class="row">
    <div class="col-sm-6 col-md-3">
    </div>
  </div>
</div>

app/views/static_pages/about.html.erb
<h1>About Us</h1>

app/views/static_pages/contact.html.erb
<h1>Contact</h1>

app/views/static_pages/home.html.erb
<script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>

<div class="center hero-unit">
  <h1>Welcome to the 個サルapp</h1>

  <h2>
		東京を中心に個人参加できるフットサルコート場の情報を収集したサイトです。
  </h2>
</div>



<div style='width: 940px;'>
  <div id="map" style='width: 940px; height: 400px;'></div>
</div>

<script type="text/javascript">
    handler = Gmaps.build('Google');
    handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
      markers = handler.addMarkers(<%=raw @hash.to_json %>);
      handler.bounds.extendWith(markers);
      handler.fitMapToBounds();
    });
</script>



<br>

<div class="center hero-unit">
<table class="table table-striped">
<%= link_to "最新情報", '#', class: "btn btn-large btn-primary" %>
<thead>
	<th width="20%">場所</th>
	<th width="20%">イベント名</th>
  <th width="20%">日時</th>
  <th width="20%">募集人数</th>
  <th width="20%">残り</th>
</thead>
<tbody>
	<% @detail.zip(@date,@url,@title).each do |item,date,url,title| %>
		<tr><td>落合南長崎</td><td><a href='<%= url %>'><%= title %></a></td><td><%= date %></td><td><%= item[0] %></td><td><%= item[1] %></td></tr>
	<% end %>
  <% @detail_toshi.zip(@date_toshi,@url_toshi,@title_toshi).each do |item,date,url,title| %>
		<tr><td>豊島園</td><td><a href='<%= url %>'><%= title %></a></td><td><%= date %></td><td><%= item[0] %></td><td><%= item[1] %></td></tr>
	<% end %>
  <% @detail_toshi.zip(@date_nerima,@url_nerima,@title_nerima).each do |item,date,url,title| %>
		<tr><td>練馬</td><td><a href='<%= url %>'><%= title %></a></td><td><%= date %></td><td><%= item[0] %></td><td><%= item[1] %></td></tr>
	<% end %>

</tbody>
</table>
</div>

app/views/static_pages/nerima.html.erb
<h1>練馬コート情報</h1>
<div class="center hero-unit">
<table class="table table-striped">
<thead>
  <th width="20%">イベント名称</th>
  <th width="20%">日時</th>
  <th width="20%">募集人数</th>
  <th width="20%">残り</th>
</thead>
<tbody>
<% @detail.zip(@date,@title,@url).each do |item,day,title,url| %>
	<tr><td><a href='<%= url %>'><%= title %></a></td><td><%= day %></td><td><%= item[0] %></td><td><%= item[1] %></td></tr>
<% end %>
</tbody>
</table>
</div>

app/views/static_pages/news.html.erb
<h1>news</h1>

app/views/static_pages/ochiai.html.erb
<h1>落合南長崎コート情報</h1>
<div class="center hero-unit">
<table class="table table-striped">
<thead>
  <th width="20%">イベント名称</th>
  <th width="20%">日時</th>
  <th width="20%">募集人数</th>
  <th width="20%">残り</th>
</thead>
<tbody>
<% @events.each do |event| %>
  <tr>
    <td><%= event.name %></td>
    <td><%= event.start_date %></td>
    <td><%= event.participants %></td>
    <td><%= event.unoccupied_seats %></td>
  </tr>
<% end %>
</tbody>
</table>
</div>

app/views/static_pages/place.html.erb
<h1>コート</h1>
<div class="center hero-unit">
<table class="table table-striped">
<thead>
  <th width="20%">場所</th>
  <th width="20%">住所</th>
  <th width="20%">料金</th>
</thead>
<tbody>
	<tr><td><%= link_to "落合南長崎", ochiai_path %></td><td>東京都豊島区南長崎４−５−20 アイテラス５F</td><td>1300円~</td></tr>
<tr><td><a href='#'>池袋</a></td><td>東京都豊島区東池袋1-5-7ヤマダ電機ＬＡＢＩ１日本総本店池袋屋上</td><td>1030円~</td></tr>
<tr><td><a href='#'>渋谷</a></td><td>東京都渋谷区渋谷2-24-1</td><td>1030円~</td></tr>
<tr><td><%= link_to "豊島園", toshimaen_path %></td><td>東京都練馬区向山3-25-1としまえん屋内館</td><td>520円~</td></tr>
<tr><td><%= link_to "練馬", nerima_path %></td><td>東京都練馬区田柄1-5-8</td><td>1100円~</td></tr>
</tbody>
</table>
</div>

app/views/static_pages/toshimaen.html.erb
<h1>豊島園コート情報</h1>
<div class="center hero-unit">
<table class="table table-striped">
<thead>
  <th width="20%">イベント名称</th>
  <th width="20%">日時</th>
  <th width="20%">募集人数</th>
  <th width="20%">残り</th>
</thead>
<tbody>
<% @detail.zip(@date,@title,@url).each do |item,day,title,url| %>
	<tr><td><a href='<%= url %>'><%= title %></a></td><td><%= day %></td><td><%= item[0] %></td><td><%= item[1] %></td></tr>
<% end %>
</tbody>
</table>
</div>